In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [2]:
dict1 = {
    "name":['r','v'],
    "age":[2,2],
    "city":['d','d']
}

In [3]:
of= pd.DataFrame(dict1)

In [4]:
of

  name  age city
0    r    2    d
1    v    2    d

In [5]:
of.to_csv("first.csv")

In [6]:
of.to_csv("first_indexFalse.csv", index=False)

In [7]:
of.head(1)

  name  age city
0    r    2    d

In [8]:
of.tail(1)

  name  age city
1    v    2    d

In [9]:
of.describe()

       age
count  2.0
mean   2.0
std    0.0
min    2.0
25%    2.0
50%    2.0
75%    2.0
max    2.0

In [10]:
harry = pd.read_csv('first.csv')

In [12]:
harry

   Unnamed: 0 name  age city
0           0    r    2    d
1           1    v    2    d

In [ ]:
harry['name']['r']='rad'

In [15]:
newdf = pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [16]:
newdf.head(4)

          0         1         2         3         4
0  0.984382  0.045374  0.067528  0.734985  0.540562
1  0.200725  0.858649  0.871891  0.134440  0.011184
2  0.107973  0.420050  0.828402  0.034943  0.442736
3  0.192398  0.417696  0.370722  0.844318  0.171345

In [17]:
type(newdf)

pandas.core.frame.DataFrame

In [18]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [19]:
newdf[0][0] = "harry"

/var/folders/st/kyt0s81n0cj83d72d319781r0000gn/T/ipykernel_32941/2771891818.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "harry"
/var/folders/st/kyt0s81n0cj83d72d319781r0000gn/T/ipykernel_32941/2771891818.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harry' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "harry"

In [20]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [21]:
newdf.head(3)

          0         1         2         3         4
0     harry  0.045374  0.067528  0.734985  0.540562
1  0.200725  0.858649  0.871891  0.134440  0.011184
2  0.107973  0.420050  0.828402  0.034943  0.442736

In [22]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [23]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [24]:
newdf.to_numpy()

array([['harry', 0.045374498079947645, 0.06752816084725421,
        0.734985260152373, 0.5405621122104429],
       [0.20072465539599638, 0.8586491461604445, 0.8718910570545376,
        0.13443953648675133, 0.011184052787936327],
       [0.1079727484309928, 0.42004953348799323, 0.8284017701279074,
        0.034942679351081196, 0.4427355430323956],
       ...,
       [0.21560101625617434, 0.7842116315378118, 0.7782272619956566,
        0.17110398386658543, 0.8370125252535197],
       [0.5632244119775964, 0.7934179257913279, 0.706777896625495,
        0.2343894241065786, 0.8970905138538464],
       [0.03821353007551864, 0.35656529275094817, 0.5174785994597694,
        0.27098655494530544, 0.5553500713683606]],
      shape=(334, 5), dtype=object)

In [25]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,harry,0.200725,0.107973,0.192398,0.748249,0.760622,0.831916,0.492697,0.242278,0.238887,...,0.988184,0.368896,0.899291,0.100532,0.316488,0.950857,0.513574,0.215601,0.563224,0.038214
1,0.045374,0.858649,0.42005,0.417696,0.784586,0.50738,0.260313,0.449968,0.09884,0.738617,...,0.385307,0.552299,0.065593,0.267892,0.432877,0.39723,0.13151,0.784212,0.793418,0.356565
2,0.067528,0.871891,0.828402,0.370722,0.642652,0.264984,0.433692,0.095949,0.317341,0.545866,...,0.186227,0.231724,0.280483,0.200588,0.403429,0.99399,0.261305,0.778227,0.706778,0.517479
3,0.734985,0.13444,0.034943,0.844318,0.646288,0.47732,0.435091,0.483027,0.9329,0.696506,...,0.655025,0.998111,0.000885,0.802888,0.232701,0.467221,0.37415,0.171104,0.234389,0.270987
4,0.540562,0.011184,0.442736,0.171345,0.180179,0.71516,0.310928,0.502765,0.814852,0.469714,...,0.318322,0.644616,0.140803,0.048373,0.785383,0.83517,0.087541,0.837013,0.897091,0.55535

In [26]:
newdf

            0         1         2         3         4
0       harry  0.045374  0.067528  0.734985  0.540562
1    0.200725  0.858649  0.871891  0.134440  0.011184
2    0.107973  0.420050  0.828402  0.034943  0.442736
3    0.192398  0.417696  0.370722  0.844318  0.171345
4    0.748249  0.784586  0.642652  0.646288  0.180179
..        ...       ...       ...       ...       ...
329  0.950857  0.397230  0.993990  0.467221  0.835170
330  0.513574  0.131510  0.261305  0.374150  0.087541
331  0.215601  0.784212  0.778227  0.171104  0.837013
332  0.563224  0.793418  0.706778  0.234389  0.897091
333  0.038214  0.356565  0.517479  0.270987  0.555350

[334 rows x 5 columns]

In [27]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.038214  0.356565  0.517479  0.270987  0.555350
332  0.563224  0.793418  0.706778  0.234389  0.897091
331  0.215601  0.784212  0.778227  0.171104  0.837013
330  0.513574  0.131510  0.261305  0.374150  0.087541
329  0.950857  0.397230  0.993990  0.467221  0.835170
..        ...       ...       ...       ...       ...
4    0.748249  0.784586  0.642652  0.646288  0.180179
3    0.192398  0.417696  0.370722  0.844318  0.171345
2    0.107973  0.420050  0.828402  0.034943  0.442736
1    0.200725  0.858649  0.871891  0.134440  0.011184
0       harry  0.045374  0.067528  0.734985  0.540562

[334 rows x 5 columns]

In [28]:
newdf[0]

0         harry
1      0.200725
2      0.107973
3      0.192398
4      0.748249
         ...
329    0.950857
330    0.513574
331    0.215601
332    0.563224
333    0.038214
Name: 0, Length: 334, dtype: object

In [29]:
type(newdf[0])

pandas.core.series.Series

In [30]:
newdf2 = newdf

In [31]:
newdf2[0][0]=972

In [32]:
newdf

            0         1         2         3         4
0         972  0.045374  0.067528  0.734985  0.540562
1    0.200725  0.858649  0.871891  0.134440  0.011184
2    0.107973  0.420050  0.828402  0.034943  0.442736
3    0.192398  0.417696  0.370722  0.844318  0.171345
4    0.748249  0.784586  0.642652  0.646288  0.180179
..        ...       ...       ...       ...       ...
329  0.950857  0.397230  0.993990  0.467221  0.835170
330  0.513574  0.131510  0.261305  0.374150  0.087541
331  0.215601  0.784212  0.778227  0.171104  0.837013
332  0.563224  0.793418  0.706778  0.234389  0.897091
333  0.038214  0.356565  0.517479  0.270987  0.555350

[334 rows x 5 columns]

In [33]:
newdf3= newdf.copy()

In [34]:
newdf3[0][0]=12

/var/folders/st/kyt0s81n0cj83d72d319781r0000gn/T/ipykernel_32941/2642551083.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0]=12
/var/folders/st/kyt0s81n0cj83d72d319781r0000gn/T/ipykernel_32941/2642551083.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0]=12

In [35]:
newdf

            0         1         2         3         4
0         972  0.045374  0.067528  0.734985  0.540562
1    0.200725  0.858649  0.871891  0.134440  0.011184
2    0.107973  0.420050  0.828402  0.034943  0.442736
3    0.192398  0.417696  0.370722  0.844318  0.171345
4    0.748249  0.784586  0.642652  0.646288  0.180179
..        ...       ...       ...       ...       ...
329  0.950857  0.397230  0.993990  0.467221  0.835170
330  0.513574  0.131510  0.261305  0.374150  0.087541
331  0.215601  0.784212  0.778227  0.171104  0.837013
332  0.563224  0.793418  0.706778  0.234389  0.897091
333  0.038214  0.356565  0.517479  0.270987  0.555350

[334 rows x 5 columns]

In [36]:
newdf3

            0         1         2         3         4
0          12  0.045374  0.067528  0.734985  0.540562
1    0.200725  0.858649  0.871891  0.134440  0.011184
2    0.107973  0.420050  0.828402  0.034943  0.442736
3    0.192398  0.417696  0.370722  0.844318  0.171345
4    0.748249  0.784586  0.642652  0.646288  0.180179
..        ...       ...       ...       ...       ...
329  0.950857  0.397230  0.993990  0.467221  0.835170
330  0.513574  0.131510  0.261305  0.374150  0.087541
331  0.215601  0.784212  0.778227  0.171104  0.837013
332  0.563224  0.793418  0.706778  0.234389  0.897091
333  0.038214  0.356565  0.517479  0.270987  0.555350

[334 rows x 5 columns]

In [37]:
newdf.loc[0,0] = 654

In [38]:
newdf.head(2)

          0         1         2         3         4
0       654  0.045374  0.067528  0.734985  0.540562
1  0.200725  0.858649  0.871891  0.134440  0.011184

In [39]:
newdf.columns = list("ABCDE")

In [41]:
newdf.head(2)

          A         B         C         D         E
0      6542  0.045374  0.067528  0.734985  0.540562
1  0.200725  0.858649  0.871891  0.134440  0.011184

In [42]:
newdf.loc[0,'A'] = 6542

In [43]:
newdf.head(2)

          A         B         C         D         E
0      6542  0.045374  0.067528  0.734985  0.540562
1  0.200725  0.858649  0.871891  0.134440  0.011184

In [44]:
newdf.drop('E', axis=1)

            A         B         C         D
0        6542  0.045374  0.067528  0.734985
1    0.200725  0.858649  0.871891  0.134440
2    0.107973  0.420050  0.828402  0.034943
3    0.192398  0.417696  0.370722  0.844318
4    0.748249  0.784586  0.642652  0.646288
..        ...       ...       ...       ...
329  0.950857  0.397230  0.993990  0.467221
330  0.513574  0.131510  0.261305  0.374150
331  0.215601  0.784212  0.778227  0.171104
332  0.563224  0.793418  0.706778  0.234389
333  0.038214  0.356565  0.517479  0.270987

[334 rows x 4 columns]

In [45]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.871891  0.134440
2  0.828402  0.034943

In [46]:
newdf.head()

          A         B         C         D         E
0      6542  0.045374  0.067528  0.734985  0.540562
1  0.200725  0.858649  0.871891  0.134440  0.011184
2  0.107973  0.420050  0.828402  0.034943  0.442736
3  0.192398  0.417696  0.370722  0.844318  0.171345
4  0.748249  0.784586  0.642652  0.646288  0.180179

In [47]:
newdf.loc[:,['C','D']]

            C         D
0    0.067528  0.734985
1    0.871891  0.134440
2    0.828402  0.034943
3    0.370722  0.844318
4    0.642652  0.646288
..        ...       ...
329  0.993990  0.467221
330  0.261305  0.374150
331  0.778227  0.171104
332  0.706778  0.234389
333  0.517479  0.270987

[334 rows x 2 columns]

In [48]:
 newdf.loc[(newdf['A']>0.8) & (newdf['C']<0.4) ]

            A         B         C         D         E
0        6542  0.045374  0.067528  0.734985  0.540562
19   0.843914  0.450438  0.316083  0.865535  0.159167
67    0.90277  0.462885  0.092514  0.897509  0.095563
90   0.884212  0.776238  0.232829  0.522289  0.934882
98   0.933662  0.052645  0.277315  0.442858  0.191243
103   0.90034  0.087813  0.246869  0.227361  0.643811
134  0.871112  0.051051  0.203977  0.887975  0.055395
142  0.996311  0.626813  0.177115  0.606024  0.406768
143  0.867281  0.128372  0.390304  0.968298  0.989128
149  0.831815  0.656738  0.303364  0.006659  0.605931
187  0.940729  0.608763  0.190221  0.886499  0.600504
193  0.972073  0.980904  0.099390  0.373084  0.806645
195  0.861483  0.393584  0.024449  0.155693  0.565143
201  0.955435  0.324727  0.288133  0.526731  0.122950
230   0.90273  0.709451  0.307731  0.811576  0.945235
236  0.949135  0.917384  0.310166  0.356375  0.219892
240  0.885539  0.188488  0.330031  0.102042  0.322961
255  0.998215  0.421637  0.075630  0.606838  0.248263
305  0.998198  0.317921  0.222759  0.648872  0.479345
313  0.805884  0.724851  0.338451  0.117640  0.322217
324  0.988184  0.385307  0.186227  0.655025  0.318322
326  0.899291  0.065593  0.280483  0.000885  0.140803

In [49]:
newdf.iloc[0,4]

np.float64(0.5405621122104429)

In [50]:
newdf.iloc[[0,4],[4,3]]

          E         D
0  0.540562  0.734985
4  0.180179  0.646288

In [51]:
newdf.drop([0])

            A         B         C         D         E
1    0.200725  0.858649  0.871891  0.134440  0.011184
2    0.107973  0.420050  0.828402  0.034943  0.442736
3    0.192398  0.417696  0.370722  0.844318  0.171345
4    0.748249  0.784586  0.642652  0.646288  0.180179
5    0.760622  0.507380  0.264984  0.477320  0.715160
..        ...       ...       ...       ...       ...
329  0.950857  0.397230  0.993990  0.467221  0.835170
330  0.513574  0.131510  0.261305  0.374150  0.087541
331  0.215601  0.784212  0.778227  0.171104  0.837013
332  0.563224  0.793418  0.706778  0.234389  0.897091
333  0.038214  0.356565  0.517479  0.270987  0.555350

[333 rows x 5 columns]

In [52]:
newdf.drop(['E','C'], axis=1)

            A         B         D
0        6542  0.045374  0.734985
1    0.200725  0.858649  0.134440
2    0.107973  0.420050  0.034943
3    0.192398  0.417696  0.844318
4    0.748249  0.784586  0.646288
..        ...       ...       ...
329  0.950857  0.397230  0.467221
330  0.513574  0.131510  0.374150
331  0.215601  0.784212  0.171104
332  0.563224  0.793418  0.234389
333  0.038214  0.356565  0.270987

[334 rows x 3 columns]

In [53]:
newdf.drop(['E','C'], axis=1, inplace=True)

In [54]:
newdf

            A         B         D
0        6542  0.045374  0.734985
1    0.200725  0.858649  0.134440
2    0.107973  0.420050  0.034943
3    0.192398  0.417696  0.844318
4    0.748249  0.784586  0.646288
..        ...       ...       ...
329  0.950857  0.397230  0.467221
330  0.513574  0.131510  0.374150
331  0.215601  0.784212  0.171104
332  0.563224  0.793418  0.234389
333  0.038214  0.356565  0.270987

[334 rows x 3 columns]

In [55]:
newdf.reset_index()

     index         A         B         D
0        0      6542  0.045374  0.734985
1        1  0.200725  0.858649  0.134440
2        2  0.107973  0.420050  0.034943
3        3  0.192398  0.417696  0.844318
4        4  0.748249  0.784586  0.646288
..     ...       ...       ...       ...
329    329  0.950857  0.397230  0.467221
330    330  0.513574  0.131510  0.374150
331    331  0.215601  0.784212  0.171104
332    332  0.563224  0.793418  0.234389
333    333  0.038214  0.356565  0.270987

[334 rows x 4 columns]

In [56]:
newdf.reset_index(drop=True, inplace=True)

In [57]:
newdf

            A         B         D
0        6542  0.045374  0.734985
1    0.200725  0.858649  0.134440
2    0.107973  0.420050  0.034943
3    0.192398  0.417696  0.844318
4    0.748249  0.784586  0.646288
..        ...       ...       ...
329  0.950857  0.397230  0.467221
330  0.513574  0.131510  0.374150
331  0.215601  0.784212  0.171104
332  0.563224  0.793418  0.234389
333  0.038214  0.356565  0.270987

[334 rows x 3 columns]

In [58]:
newdf.loc[:,['B']]=None

/var/folders/st/kyt0s81n0cj83d72d319781r0000gn/T/ipykernel_32941/1512160642.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf.loc[:,['B']]=None

In [59]:
newdf

            A     B         D
0        6542  None  0.734985
1    0.200725  None  0.134440
2    0.107973  None  0.034943
3    0.192398  None  0.844318
4    0.748249  None  0.646288
..        ...   ...       ...
329  0.950857  None  0.467221
330  0.513574  None  0.374150
331  0.215601  None  0.171104
332  0.563224  None  0.234389
333  0.038214  None  0.270987

[334 rows x 3 columns]

In [60]:
newdf.loc[:,['B']]=69

In [61]:
newdf

            A   B         D
0        6542  69  0.734985
1    0.200725  69  0.134440
2    0.107973  69  0.034943
3    0.192398  69  0.844318
4    0.748249  69  0.646288
..        ...  ..       ...
329  0.950857  69  0.467221
330  0.513574  69  0.374150
331  0.215601  69  0.171104
332  0.563224  69  0.234389
333  0.038214  69  0.270987

[334 rows x 3 columns]

In [62]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       334 non-null    object
 1   B       334 non-null    object
 2   D       334 non-null    float64
dtypes: float64(1), object(2)
memory usage: 8.0+ KB

In [63]:
newdf.isnull()

         A      B      D
0    False  False  False
1    False  False  False
2    False  False  False
3    False  False  False
4    False  False  False
..     ...    ...    ...
329  False  False  False
330  False  False  False
331  False  False  False
332  False  False  False
333  False  False  False

[334 rows x 3 columns]